### ISSUE TITLE
[Sway] Cannot run

### ISSUE THREAD

**Issue by ductri** [moustacheful/glimmer#5]
Hi,

When I run `cargo run`, I got this error:
```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/glimmer`
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: Error("unknown variant `none`, expected one of `splith`, `splitv`, `stacked`, `tabbed`, `dockarea`, `output`", line: 1, column: 181) }', src/actors/i3_ipc.rs:74:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Cargo and Rust version:
```
$ cargo --version
cargo 1.53.0 (4369396ce 2021-04-27)
```
```
$ rustc --version
rustc 1.53.0 (53cb7b09b 2021-06-17)
```
Really like the idea, so I really want to try it.

**Comment by moustacheful** [comment]
Hey @ductri thanks for reporting this. What version of i3 are you running? or is it maybe Sway? wondering if it has something to do with that.

**Comment by ductri** [comment]
I'm running Sway. 
```
$ sway --version
sway version 1.6-1a0f86be (Apr 10 2021, branch 'master')
```

**Comment by moustacheful** [comment]
Thanks for that. It seems like that Sway produces some message that doesn't sit well with [tokio-i3-ipc](https://crates.io/crates/tokio-i3ipc). 

After taking a look, it seems sway is only supported when enabling a feature on said library, because of [this](https://github.com/leshow/tokio-i3ipc/blob/master/i3ipc-types/src/reply.rs#L259-L260). So apparently Sway _does_ have a couple of differences. 

Could you help me confirm this? try cloning the repo, and on `cargo.toml` replace

```toml
tokio-i3ipc = "0.12.1"
```

with
```toml
tokio-i3ipc = { version: "0.12.1", features: ["sway"] }
```

and then run `cargo build && cargo run`

Let me know if that works, if it does, I can later enable a feature on this crate and maybe create precompiled versions for both.

**Comment by ductri** [comment]
I got a syntax error
```
$ cargo build
error: failed to parse manifest at `/home/tringuyen/build_tools/glimmer/Cargo.toml`

Caused by:
  could not parse input as TOML

Caused by:
  expected an equals, found a colon at line 18 column 24
```

**Comment by ductri** [comment]
Okay, ":" should be substituted by "=", then the building process is successful. 
But then, `cargo run` still got error

```
$ RUST_BACKTRACE=full cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/glimmer`
thread 'main' panicked at 'Could not read css file!: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/gtk_utils.rs:13:43
stack backtrace:
   0:     0x5570dbf4dc20 - std::backtrace_rs::backtrace::libunwind::trace::ha5edb8ba5c6b7a6c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5570dbf4dc20 - std::backtrace_rs::backtrace::trace_unsynchronized::h0de86d320a827db2
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5570dbf4dc20 - std::sys_common::backtrace::_print_fmt::h97b9ad6f0a1380ff
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5570dbf4dc20 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h14be7eb08f97fe80
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5570dbf7193f - core::fmt::write::h2ca8877d3e0e52de
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
   5:     0x5570dbf4ae85 - std::io::Write::write_fmt::h64f5987220b618f4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
   6:     0x5570dbf4fceb - std::sys_common::backtrace::_print::h7f1a4097308f2e0a
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5570dbf4fceb - std::sys_common::backtrace::print::h1f799fc2ca7f5035
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5570dbf4fceb - std::panicking::default_hook::{{closure}}::hf38436e8a3ce1071
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
   9:     0x5570dbf4f7bd - std::panicking::default_hook::he2f8f3fae11ed1dd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:225:9
  10:     0x5570dbf502fd - std::panicking::rust_panic_with_hook::h79a18548bd90c7d4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:591:17
  11:     0x5570dbf4fe97 - std::panicking::begin_panic_handler::{{closure}}::h212a72cc08e25126
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:497:13
  12:     0x5570dbf4e0bc - std::sys_common::backtrace::__rust_end_short_backtrace::hbd6897dd42bc0fcd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x5570dbf4fdf9 - rust_begin_unwind
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
  14:     0x5570dbbc3221 - core::panicking::panic_fmt::h77ecd04e9b1dd84d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
  15:     0x5570dbbc3313 - core::result::unwrap_failed::hcbdf25d28ce8f0ca
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1355:5
  16:     0x5570dbc20bd7 - core::result::Result<T,E>::expect::hd359208dcc1eb811
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:997:23
  17:     0x5570dbbf2343 - glimmer::gtk_utils::setup::hac62f6f6e035f578
                               at /home/tringuyen/build_tools/glimmer/src/gtk_utils.rs:13:16
  18:     0x5570dbbe86d9 - glimmer::main::hff5308c35c3aa2c8
                               at /home/tringuyen/build_tools/glimmer/src/main.rs:20:5
  19:     0x5570dbbf419b - core::ops::function::FnOnce::call_once::h3aa8f4b1e351cba9
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
  20:     0x5570dbc1416e - std::sys_common::backtrace::__rust_begin_short_backtrace::h47f6fd98c011022f
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:125:18
  21:     0x5570dbbf38e1 - std::rt::lang_start::{{closure}}::h2b73e58b787960da
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/rt.rs:49:18
  22:     0x5570dbf506fa - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc4354216bf39217c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:259:13
  23:     0x5570dbf506fa - std::panicking::try::do_call::hb68eb312780385cf
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
  24:     0x5570dbf506fa - std::panicking::try::h22b8e08595060b8b
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
  25:     0x5570dbf506fa - std::panic::catch_unwind::hc64f1a6a0e71b1fc
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
  26:     0x5570dbf506fa - std::rt::lang_start_internal::h4461fc58637f04f8
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/rt.rs:34:21
  27:     0x5570dbbf38c0 - std::rt::lang_start::h627db6be36e551b3
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/rt.rs:48:5
  28:     0x5570dbbe8eac - main
  29:     0x7fda68887cb2 - __libc_start_main
  30:     0x5570dbbc39be - _start
  31:                0x0 - <unknown>
```

**Comment by moustacheful** [comment]
> Okay, ":" should be substituted by "=", then the building process would success.
> But then, `cargo run` still got error
> 
> ```
> $ RUST_BACKTRACE=full cargo run
>     Finished dev [unoptimized + debuginfo] target(s) in 0.06s
>      Running `target/debug/glimmer`
> thread 'main' panicked at 'Could not read css file!: Os { code: 2, kind: NotFound, message: "No such file or directory" }',
> ```

Ah but you're so close! you just need to specify a styles file. I made a couple small changes on how these work and now there's no default.

try doing:

```
cargo build && cargo run -- --styles=./themes/flash.css
```

**Comment by ductri** [comment]
Now it ran without error. But then the moment I change windows, there is a window flashing rapidly :(. Yeah, I'm getting closed but not quite there yet. 
```
 to position it on screen.
Gdk-Message: 14:27:41.949: Window 0x55746195ed20 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 14:27:41.990: Window 0x5574619623c0 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 14:27:41.998: Window 0x557461962700 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 14:27:42.036: Window 0x55746195e9e0 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 14:27:42.043: Window 0x557461962560 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 14:27:42.108: Window 0x557461962a40 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 14:27:42.118: Window 0x557461962d80 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 14:27:42.156: Window 0x557461962220 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 14:27:42.165: Window 0x557461962be0 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 14:27:42.238: Window 0x557461966290 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 14:27:42.248: Window 0x5574619665d0 is a temporary window without parent, application will not be able to position it on screen.
```

**Comment by moustacheful** [comment]
Gave it a try on a VM and ran into the same issue as you did.
It seems that the GDK/GTK backend for Wayland ignores both the windows being unfocusable and unclickable, as well as not being able to be positioned properly, so I think we're out of luck with giving Sway support :(

I set up a branch `feat/sway` which has a patch for the window flickering (seems like since the windows are focusable in Wayland, they trigger a decoration for each other), and I added a rule to Sway as follows:

```
no focus [title="__GLIMMER_WINDOW__"]
```

which helped a bit but the results are still not good enough.

If you're feeling adventurous feel free to give it a try and see how it could be fixed, but I couldn't find a lot.

**Comment by ductri** [comment]
I installed and ran successfully on my i3wm using `cargo build && cargo run -- --styles=./themes/flash.css`. 

Greatly thank you for your help and your contribution. I have no experience with rust and little experience with whatever glimmer's implementation, never dig into these kind of window manager related codes. I'd guess I have to go on without your glimmer on Sway for near future :) . I'll close the issue now.
